### ISSUE TITLE
Blinking Images in first play in Edge and Firefox Developer Edition

### ISSUE THREAD

**Issue by kornbed** [konsultaner/jsMovie#12]

**Comment by iovzt** [comment]
Hi, I have fixed it in such a way:

css:
.jsMovieFrame { position: absolute; left: 0; top: 0; }
js:
var $bannerAnim; // it is parent block
$bannerAnim.on("loaded": function () {
      $(".jsMovieFrame", $bannerAnim).show();
      setTimeout(function() {
            $(".jsMovieFrame", $bannerAnim).hide();
            $bannerAnim.jsMovie("play");
      }, 100);                            
}).jsMovie({
      playOnLoad: false,
      ...
});

**Comment by esra84** [comment]
Hi, can you explain how you fixed it?
I have the following code:
var played = 0;
    $(document).ready(function() {
        //$('.paket_ani').jsMovie({
        $('.paket_ani').jsMovie({
            sequence: "basis_0####.png", //the #### will be replaced with 0001,0002,0003,...
            folder: 'myfolder/', //this is the path where the script can find the image sequence
            from: 1, //the #### will start to replace with 0001
            to: 49, //the #### will start to replace with 0040
            width: 400, //the advertisement container will be resized to a width of 320px
            height: 400, //the advertisement container will be resized to a height of 150px
            repeat: false,
            fps: 30,
            showPreLoader: false, //we do want to see a preloader animation
            playOnLoad: false, //we don't want to have the movie play after the images have been loaded automatically
            // the preloader animation is located in the folder "img/loader.png"
            // it is a 4x4 image matrix with each image of 40px by 40px
            loader: {
                path: "img/loader.png",
                height: 40,
                width: 40,
                rows: 4,
                columns: 4
            }
        });
$(window).scroll(function() {
            var scroll_height = $window.scrollTop();
            if ($('.myimage_ani').length > 0) {
                $('.myimage_ani').stop().animate({"marginTop": "765px"}, "slow", function() {
                    // Animation complete.
                    if (($('.myimage_ani').css("margin-top") === "765px") && (played == 0)) {
                        played = 1;
                        $('.myimage_ani').jsMovie("addClip", "My_Topic", 1, 49);
                        // play both the clips
                        $('.myimage_ani').jsMovie("playClips");
                        $('.myimage_ani').on('ended', function() {
                            $('.right_mycustom_box').fadeIn(800);
                        });

                    }
                });

            }
        });
How can I fix it here?
I would be happy about an explanation.

**Comment by konsultaner** [comment]
i fixed it with the last commit
